---

- name: Create custom facts directory
  ansible.builtin.file:
    path: "{{ facts_path }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Convert facts configuration into the latest format
  ansible.builtin.set_fact:
    _facts: >-
      {{ _facts|default([]) +
        [ {
          'name': (item.name|default(item)),
          'groups': [item.group] if item.group is defined else (item.groups|default('all')),
          'os': (item.os | default('all')),
          'os_family': (item.os_family | default('all'))
        } ]
      }}
  loop: "{{ facts_custom + facts_custom_additional }}"

- name: Distributes custom facts
  ansible.builtin.template:
    src: "{{ item.name }}.fact.j2"
    dest: "{{ facts_path }}/{{ item.name }}.fact"
    mode: '0755'
  loop: "{{ _facts }}"
  register: _facts_results
  when:
    - item.groups == 'all' or group_names|intersect(item.groups)|length > 0
    - item.os == 'all' or ansible_distribution in item.os
    - item.os_family == 'all' or ansible_os_family in item.os_family

- name: Execute setup
  ansible.builtin.setup:
  when:
    - facts_run_setup|bool
    - _facts_results.changed
