---

- name: Create custom facts directory
  file:
    path: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Distributes generic custom facts
  template:
    src: "{{ item }}.fact.j2"
    dest: /etc/ansible/facts.d/{{ item }}.fact
    mode: '0755'
  loop: "{{ custom_facts }}"
  notify: Run setup
  
- name: Distribute specific custom facts
  template:
    src: "{{ item.name }}.fact.j2"
    dest: /etc/ansible/facts.d/{{ item.name }}.fact
    mode: '0755'
  loop: "{{ custom_facts_additional }}"
  when: item.group is undefined or inventory_hostname in groups[item.group]
  notify: Run setup
