---

- name: Create custom facts directory
  ansible.builtin.file:
    path: "{{ facts_path }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: ansible_os_family != 'Windows'

- name: Distributes custom facts
  ansible.builtin.template:
    src: "{{ fact.name }}.fact.j2"
    dest: "{{ facts_path }}/{{ fact.name }}.fact"
    mode: '0755'
  loop: "{{ _facts }}"
  loop_control:
    loop_var: fact
  register: _facts_results
  when:
    - fact.groups == 'all' or group_names | intersect(fact.groups)| length > 0
    - fact.os == 'all' or ansible_distribution in fact.os
    - fact.os_family == 'all' or ansible_os_family in fact.os_family

- name: Execute setup
  ansible.builtin.setup:
    fact_path: "{{ facts_path }}"
  when: facts_force_run_setup | bool or ( facts_run_setup | bool and _facts_results.changed )
