---

- name: Install packages needed (Debian-family)
  ansible.builtin.apt:
    name: "{{ facts_packages }}"
    state: present
    update_cache: true
  become: true
  when: ansible_facts.os_family == 'Debian'

- name: Install packages needed (RedHat-family)
  ansible.builtin.dnf:
    name: "{{ facts_packages }}"
    state: present
  become: true
  when: ansible_facts.os_family == 'RedHat'

- name: Install packages needed (Suse-family)
  community.general.zypper:
    name: "{{ facts_packages }}"
    state: present
  become: true
  when: ansible_facts.os_family == 'Suse'

- name: Install components in python venv
  ansible.builtin.pip:
    name: "{{ item.packages }}"
    virtualenv: /usr/local/venv/{{ item.name }}
    virtualenv_command: python3 -m venv
  become: true
  loop: "{{ facts_venv }}"

- name: Create custom facts directory
  ansible.builtin.file:
    path: "{{ facts_path }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Distributes custom facts
  ansible.builtin.template:
    src: "{{ fact.name }}.fact.j2"
    dest: "{{ facts_path }}/{{ fact.name }}.fact"
    mode: '0755'
  become: true
  loop: "{{ _facts }}"
  loop_control:
    loop_var: fact
  register: _facts_results
  when:
    - fact.groups == 'all' or group_names | intersect(fact.groups)| length > 0
    - fact.os == 'all' or ansible_facts.distribution in fact.os
    - fact.os_family == 'all' or ansible_facts.os_family in fact.os_family

- name: Execute setup
  ansible.builtin.setup:
    fact_path: "{{ facts_path }}"
  when: facts_force_run_setup | bool or ( facts_run_setup | bool and _facts_results.changed )
