---

- name: Create custom facts directory
  ansible.windows.win_file:
    path: "{{ facts_path }}"
    state: directory

- name: Distributes custom facts
  ansible.windows.win_template:
    src: "windows/{{ fact.name }}.ps1.j2"
    dest: "{{ facts_path }}/{{ fact.name }}.ps1"
  loop: "{{ _facts }}"
  loop_control:
    loop_var: fact
  register: _facts_results
  when:
    - fact.groups == 'all' or group_names | intersect(fact.groups)| length > 0
    - fact.os == 'all' or ansible_distribution in fact.os
    - fact.os_family == 'all' or ansible_os_family in fact.os_family

- name: Execute setup
  ansible.builtin.setup:
    fact_path: "{{ facts_path }}"
  retries: 3
  delay: 5
