---

- name: Convert facts configuration into the latest format
  ansible.builtin.set_fact:
    _facts: >-
      {{ _facts | default([]) +
        [ {
          'name': (fact.name | default(fact)),
          'groups': [fact.group] if fact.group is defined else (fact.groups | default('all')),
          'os': (fact.os | default('all')),
          'os_family': (fact.os_family | default('all'))
        } ]
      }}
  loop: "{{ facts_custom + facts_custom_additional }}"
  loop_control:
    loop_var: fact
