---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    windows_storage: {'disks': [{'disk_number': 1}, {'disk_number': 2}], 'partitions': {'absent': [{'disk_number': 1, 'partition_number': 1}, {'disk_number': 1, 'partition_number': 2}, {'disk_number': 2, 'partition_number': 1}], 'present': [{'disk_number': 1, 'drive_letter': 'X', 'file_system': 'ntfs', 'partition_number': 1, 'partition_size': '100 MiB'}, {'disk_number': 1, 'drive_letter': 'Y', 'file_system': 'ntfs', 'partition_number': 2, 'partition_size': '200 MiB'}, {'disk_number': 2, 'drive_letter': 'Z', 'file_system': 'ntfs', 'partition_number': 1, 'partition_size': -1}]}}
  tasks:
    - name: Include role 'ansible-role-windows_storage'
      ansible.builtin.include_role:
        name: ansible-role-windows_storage
