---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    custom_facts_additional: [{'name': 'fact1', 'groups': 'all'}, {'name': 'fact2', 'os_family': ['RedHat']}, {'name': 'fact3', 'group': 'group1'}, {'name': 'fact4', 'groups': ['group2']}]
  tasks:
    - name: Include role 'ansible-role-facts'
      ansible.builtin.include_role:
        name: ansible-role-facts

- name: Converge post playbook
  ansible.builtin.import_playbook: converge-post.yml
  when: molecule_converge_post is undefined or molecule_converge_post | bool
